### ISSUE TITLE
How to run training the agent?

### ISSUE THREAD

**Issue by AOZMH** [batuhan-ince/RL_pysc2#5]
Hi. Many thanks for the great project, but I failed to find an entry point of the code (i.e. the script to start training the agent), could you please give more instruction or documentation about that? Thanks!

**Comment by Vulwsztyn** [comment]
I would extend the questions scope to "How to run anything in this repo?".

**Comment by batuhan-ince** [comment]
Sorry for late response, this version of the project is deprecated so you can't work on this repo. Currently, we're working on the new version of pysc2 and we'll update this repo as soon as possible.

**Comment by Vulwsztyn** [comment]
Would you mind adding a big red flashing "THIS REPO IS DEPRECATED" on the top of readme, so that others do not waste their time?
